### PR TITLE
update for 1.9 k8s, ansible 2.4 and add LB support.

### PR DESCRIPTION
**Pull request by mjudeikis**
Adding support for k8s 1.9
Adding support for 2.4 ansible
Adding hypriot 1.7.1 support
Adding traefik support as part of management 
Add few debug packages on the nodes (sorry, vim over vi :) )

### CODE REVIEW

**Comment by rhuss** [comment]
@mjudeikis awesome, thanks ! Let me find a free timeslot to revisit it and integrate it ... (just have to run it on my own ;-)

**Comment by mjudeikis** [comment]
@rhuss thanks :) I will try rebuild mine too as I got some additional hardware to play with :D

**Comment by rhuss** [comment]
Just did a rebuild, and except some minor issues works nicely for me, too.

Since most paint was the configuration change for a headless setup in Hypriot 1.7, so that I had to introduce a wrapper script for setting up the configuration files for cloud-init.

I'm going to polish the docs a bit, maybe moving traefik to an own playbook, but will merge the PR soonish.

Thanks a lot again !

**Comment by mjudeikis** [comment]
NP :D RedHatter is always Redhatter :D

**Comment by rhuss** [comment]
Ooops, forgot to merge ;-) Thanks again, the cluster run reliably here since somedays. I had to switch to weave for CNI as I had initially problems with flannel. will revisit this later.

Thanks!

**Pull request merged**
