### PR TITLE
Changed username according to latest Hypriot version, 1.4

### PR DESCRIPTION
**Pull request by openwms**

### CODE REVIEW

**Comment by rhuss** [comment]
Actual, user `pi` is correct here as it is introduced in the base [setup](https://github.com/Project31/ansible-kubernetes-openshift-pi3/blob/master/roles/base/tasks/user.yml#L7-L8). So you have both, `pi` and `pirate` but like `pi` better as it is shorted. It also get the public ssh key in it ~/.ssh so its even easier to login.

**Comment by rhuss** [comment]
Thanks btw ;-) The typo with `u` is already fixed in master. Please let me know whether it works for you or if something can be improved.

btw, I'm hopefully going to update to Kubernetes 1.6.2 today.

**Comment by openwms** [comment]
Strange. It didn't work with user `pi`. I had to change to `pirate`. Even no ssh login is possible with `pi` user anymore with latest Hypriot 1.4. Anyway, thanks for feedback.

**Comment by rhuss** [comment]
@openwms Did you run the setup playbook before the kubernetes playbook ?

```
ansible-playbook -k -i hosts setup.yml
```

As you can see in setup.yml `pirate` is used to setting up the base system.

**Pull request closed without merging**
